import './globals.css'
import '@radix-ui/themes/styles.css';

import Home from './page';
import { Merriweather } from 'next/font/google'
import type { Metadata } from 'next'
import Navbar from './components/Navbar'
import ScrollingBackground from './scrollingBckgrnd';
import dynamic from 'next/dynamic';

// import { Theme } from '@radix-ui/themes';

const merriweather = Merriweather({ weight: "400", subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const sectionIds = ['section1', 'section2', 'section3'];

  return (
    <>
    <html lang="en">
        <body className={merriweather.className}>
          <Navbar sectionIds={sectionIds}/>
           <ScrollingBackground />
            {children}
        </body>
    </html>
  </>
  )
}
